# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'CMLab'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: '偽編舞', url: 'pseudo'}
- {name: '仿山水', url: 'imitative'}
- {name: '人工美', url: 'artificial'}
- {name: '技|藝',  url: 'techart'}
- {name: '美|學',  url: 'about'}
#- {name: 'Contact',            url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'university', link:    'https://iaa.nctu.edu.tw/'}
- {icon: 'envelope', link:   'mailto:chimin.hsieh@gmail.com'}
# - {icon: 'university', link:   'https://www.nycu.edu.tw/'}
# - {icon: 'instagram', link:  'https://instagram.com/paululele'}
# - {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
